### ISSUE TITLE
luarocks make rockspec/shenyu-nginx-main-0.rockspec  ERROR

### ISSUE THREAD

**Issue by 521God** [apache/incubator-shenyu-nginx#27]
Missing dependencies for shenyu-nginx:
stringy == 0.7-0
lua-cjson == 2.1.0.6-1
lua-resty-http >= 0.15

Using http://www.luarocks.org/repositories/rocks/stringy-0.7-0.src.rock... switching to 'build' mode
Archive:  /tmp/luarocks_luarocks-rock-stringy-0.7-0-4414/stringy-0.7-0.src.rock
  inflating: stringy-0.7-0.rockspec  
 extracting: v0.7-0.tar.gz           
gcc -O2 -fPIC -I/home/tools/redis-5.0.5/deps/lua/src/ -c stringy/stringy.c -o stringy/stringy.o -Istringy/
stringy/stringy.c: 在函数‘join’中:
stringy/stringy.c:182:5: 错误：只允许在 C99 模式下使用‘for’循环初始化声明
     for (int i = 2; i <= top; ++i) {
     ^
stringy/stringy.c:182:5: 附注：使用 -std=c99 或 -std=gnu99 来编译您的代码

Error: Failed installing dependency: http://www.luarocks.org/repositories/rocks/stringy-0.7-0.src.rock - Build error: Failed compiling object stringy/stringy.o

**Comment by impactCn** [comment]
This is a compiler version issue, if there are no other issues I will close this.
